language: node_js
node_js:
  - "8.11.3"

branches:
  only:
    - master

before_script:

script:
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change